# Paths
output_dir: ./output/
data_dir: ../Data/LR/
model_dir: ./models/
#pretrained_models
edsr_model: 'G:\\Gachon Masters\\RESISR\\models\\EDSR_x4.pb'
espcn_model: 'G:\\Gachon Masters\\RESISR\\models\\ESPCN_x4.pb'
fsrcnn_model: 'G:\\Gachon Masters\\RESISR\\models\\FSRCNN_x4.pb'
lapsrn_model: ./pretrained_models/LapSRN_x4.pb
#custom_model
#weighted_model: ./pretrained_models/weights-wdsr-b-32-x4.pd

#input images

#action
input_dir: ./input/

#input images
